services:
  website:
    build:
      context: .
      dockerfile: deploy/Dockerfile.monorepo
      target: website
    container_name: enei-website
    ports:
      - "3333:3333"
    env_file:
      - apps/website/.env.production
      - apps/website/.env.production.local

  website-nginx:
    build:
      context: .
      dockerfile: deploy/Dockerfile.nginx
    ports:
      - "80:80"
