services:
  website:
    build:
      context: .
      dockerfile: deploy/Dockerfile.website
    volumes:
      - website-tmp:/app/tmp/
    expose:
      - "3333"
    environment:
      # Entrypoint environment variables
      - "ON_STARTUP_ENSURE_APP_KEY=${ON_STARTUP_ENSURE_APP_KEY:-false}"
      - "ON_STARTUP_MIGRATE=${ON_STARTUP_MIGRATE:-false}"
      # Project environment variables
      - "HOST=0.0.0.0"
      - "PORT=3333"
      - "TZ=${TZ:-UTC}"
      - "LOG_LEVEL=${LOG_LEVEL:-info}"
      - "APP_KEY=${APP_KEY}"
      - "SESSION_DRIVER=${SESSION_DRIVER:-cookie}"
      - "REDIS_HOST=${REDIS_HOST:-valkey}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "FROM_EMAIL=${FROM_EMAIL:-noreply@eneiconf.pt}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "INERTIA_PUBLIC_TZ=${INERTIA_PUBLIC_TZ:-Europe/Lisbon}"
      - "INERTIA_PUBLIC_EVENT_COUNTDOWN_DATE=${INERTIA_PUBLIC_EVENT_COUNTDOWN_DATE:-2025-04-11}"
      - "INERTIA_PUBLIC_APP_URL=${INERTIA_PUBLIC_APP_URL}"

  valkey:
    image: valkey/valkey:8-alpine
    command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - valkey-data:/data
    environment:
      - "VALKEY_EXTRA_FLAGS=${VALKEY_EXTRA_FLAGS}"

volumes:
  website-tmp:
  valkey-data:
