services:
  website:
    build:
      context: .
      dockerfile: deploy/Dockerfile.website
    container_name: enei-website
    ports:
      - "3333:3333"

  website-nginx:
    build:
      context: .
      dockerfile: deploy/Dockerfile.nginx
    ports:
      - "80:80"

  keycloak:
    build:
      context: .
      dockerfile: deploy/Dockerfile.keycloak
    container_name: keycloak
    env_file: "sso/.env"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8080:8080