services:
  website:
    build:
      context: .
      dockerfile: deploy/Dockerfile.website
    container_name: enei-website
    ports:
      - "3333:3333"
    environment:
      # Override NODE_ENV defined in website/.env
      - NODE_ENV=production
      - HOST=0.0.0.0
    env_file:
      - website/.env

  website-nginx:
    build:
      context: .
      dockerfile: deploy/Dockerfile.nginx
    ports:
      - "80:80"
