services:
  website:
    build:
      context: .
      dockerfile: deploy/Dockerfile.website
    container_name: enei-website
    ports:
      - "3333:3333"

  website-nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx-website.conf:/etc/nginx/nginx.conf
