services:
  mailpit:
    image: axllent/mailpit
    container_name: enei-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  valkey:
    image: valkey/valkey:8-alpine
    container_name: enei-valkey
    volumes:
      - valkey-data:/data
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  valkey-data:
  postgres-data:
