packages:
  - apps/backend
  - apps/frontend
  - packages/data
  - packages/emails
  - packages/prettier-config
  - packages/shadcn
  - packages/typescript-config
  - packages/utils
  - packages/vite-config
  
onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - msw
  - sharp
