packages:
  - "apps/*"
  - "packages/*"

catalog:
  tailwindcss: ^4.0.6
  vite: ^6.1.0
  typescript: ~5.7.3
  "@tailwindcss/vite": ^4.0.6
  zod: ^3.24.1
  lucide-react: ^0.475.0
  react: ^19.0.0
  react-dom: ^19.0.0
  react-hook-form: ^7.54.2

  "@eslint/js": ^9.19.0
  eslint: ^9.19.0

  "@turbo/gen": ^2.4.2
  "@vitejs/plugin-react": "^4.3.4"

  "vite-plugin-dts": "^4.5.0"
  "vite-plugin-externalize-deps": "^0.9.0"