packages:
  # - "apps/*"
  # - "packages/*"
  - packages/data
  - packages/emails
  - packages/prettier-config
  - packages/shadcn
  - packages/typescript-config
  - packages/utils
  - packages/vite-config
