services:
  website:
    build:
      context: ../website
      dockerfile: Dockerfile.website
    container_name: enei-website
    ports:
      - "3333:3333"

  website-nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ../website/nginx.conf:/etc/nginx/nginx.conf
