name: Website Code Checks

on:
  push:
    branches:
      - main
    paths: ["website/**"]
  pull_request:
    branches:
      - main
    paths: ["website/**"]

jobs:
  format:
    name: Linting
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            website

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint
