name: Website Code Checks

on:
  push:
    branches:
      - main
    paths: ["website/**"]
  pull_request:
    branches:
      - main
    paths: ["website/**"]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            website

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: website/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

  typecheck:
    name: Typechecking
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            website

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: website/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

  